
services:
  komodo-database:
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    container_name: komodo-database
    environment:
      POSTGRES_DB: ${KOMODO_DATASOURCE_NAME}
      POSTGRES_USER: ${KOMODO_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${KOMODO_DATASOURCE_PASSWORD}
      KOMODO_ADMIN_USERNAME: ${KOMODO_ADMIN_USERNAME}
      KOMODO_ADMIN_EMAIL: ${KOMODO_ADMIN_EMAIL}
      KOMODO_ADMIN_GIVENNAME: ${KOMODO_ADMIN_GIVENNAME}
      KOMODO_ADMIN_LASTNAME: ${KOMODO_ADMIN_LASTNAME}
      KOMODO_ADMIN_PASSWORD: ${KOMODO_ADMIN_PASSWORD}
    volumes:
      - komodo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    networks:
      - komodo-network

  redis:
    image: redis:latest
    container_name: komodo-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - komodo-network

volumes:
  komodo-db-data:
  redis-data:

networks:
  komodo-network:
    driver: bridge