version: '3.8'

services:
  komodo-database:
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    container_name: komodo-database
    environment:
      POSTGRES_DB: ${KOMODO_DATASOURCE_NAME}
      POSTGRES_USER: ${KOMODO_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${KOMODO_DATASOURCE_PASSWORD}
      KOMODO_ADMIN_USERNAME: ${KOMODO_ADMIN_USERNAME}
      KOMODO_ADMIN_EMAIL: ${KOMODO_ADMIN_EMAIL}
      KOMODO_ADMIN_GIVENNAME: ${KOMODO_ADMIN_GIVENNAME}
      KOMODO_ADMIN_LASTNAME: ${KOMODO_ADMIN_LASTNAME}
      KOMODO_ADMIN_PASSWORD: ${KOMODO_ADMIN_PASSWORD}
    volumes:
      - komodo-db-data:/var/lib/postgresql/data  # Persist DB data
    networks:
      - komodo-network

  komodo-backend:
    build:
      context: .
      dockerfile: ./Dockerfile  # Path to your Spring application's Dockerfile
    container_name: komodo-backend
    environment:
      KOMODO_JWT_SECRET_KEY: ${KOMODO_JWT_SECRET_KEY}
      KOMODO_JWT_EXPIRATION_TIME: ${KOMODO_JWT_EXPIRATION_TIME}
      KOMODO_JWT_EMAIL_VERIFICATION_TIME: ${KOMODO_JWT_EMAIL_VERIFICATION_TIME}
      KOMODO_MAILGUN_KEY: ${KOMODO_MAILGUN_KEY}
      KOMODO_MAILGUN_DOMAIN: ${KOMODO_MAILGUN_DOMAIN}
      KOMODO_DATASOURCE_URL: ${KOMODO_DATASOURCE_URL}
      KOMODO_DATASOURCE_USER: ${KOMODO_DATASOURCE_USER}
      KOMODO_DATASOURCE_PASSWORD: ${KOMODO_DATASOURCE_PASSWORD}
      KOMODO_DOMAIN_URL: ${KOMODO_DOMAIN_URL}
      KOMODO_REDIS_HOST: redis  # Redis host (same as the service name)
      KOMODO_REDIS_PORT: 6379   # Redis port
    networks:
      - komodo-network
    command: ["/wait-for-it.sh", "komodo-database:5432", "--", "java", "-jar", "/app/app.jar"]
    depends_on:
      - komodo-database
      - redis  # Ensure Redis starts before the backend

  redis:
    image: redis:latest
    container_name: komodo-redis
    ports:
      - "6379:6379"  # Expose Redis port (optional, only if you need external access)
    volumes:
      - redis-data:/data  # Persist Redis data
    networks:
      - komodo-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy/conf.d:/etc/nginx/conf.d  # Mount Nginx configuration (add on server)
      - ./nginx/nginx-proxy/certs:/etc/nginx/certs    # Mount SSL certificates (add on server)
      - ./nginx/nginx-proxy/html:/usr/share/nginx/html  # Mount static files (optional)
    networks:
      - komodo-network
    depends_on:
      - komodo-backend

volumes:
  komodo-db-data:
  redis-data:  # Volume for Redis data persistence

networks:
  komodo-network:
    driver: bridge
    