server:
  port: 8080

logging:
  level:
    '[org.springframework.security]': DEBUG
    '[kjistik.auth_server_komodo.Security]': DEBUG
    '[kjistik.auth_server_komodo.Exceptions]': WARN
    '[kjistik]': INFO
  file:
    name: logs/auth-server.log
    max-size: 10MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %logger{36} | %X{traceId:-} | %msg%n"
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(| %-5level |){blue}
      %clr(%logger{36}){cyan}
      %clr(| %X{traceId:-} |){magenta}
      %msg%n%throwable

spring:
  cloud:
    vault:
      uri: ${VAULT_ADDR:https://192.168.58.2:30000}
      authentication: ${VAULT_AUTH_METHOD:APPROLE}
      app-role:
        role-id: ${VAULT_ROLE_ID:}
        secret-id: ${VAULT_SECRET_ID:}
      transit:
        key-path: ${VAULT_TRANSIT_KEY_PATH:}
        sign-path: ${VAULT_TRANSIT_SIGN_PATH:}
      fail-fast: true

  data:
    redis:
      host: ${KOMODO_REDIS_HOST:redis}
      port: ${KOMODO_REDIS_PORT:6379}

  r2dbc:
    url: ${KOMODO_DATASOURCE_URL:r2dbc:postgresql://komodo-database:5432/komodo}
    username: ${KOMODO_DATASOURCE_USER:kjistik}
    password: ${KOMODO_DATASOURCE_PASSWORD:}

  komodo:
    domain-url: ${KOMODO_DOMAIN_URL:http://localhost:8080}

jwt:
  expiration-time: ${KOMODO_JWT_EXPIRATION_TIME:900000}
  verification-expiration-time: ${KOMODO_JWT_EMAIL_VERIFICATION_TIME:10800000}
  refresh-expiration-time: ${KOMODO_REFRESH_TOKEN_EXPIRATION_TIME:2592000000}

mailgun:
  key: ${KOMODO_MAILGUN_KEY:}
  domain: ${KOMODO_MAILGUN_DOMAIN:}

komodo_admin:
  email: ${KOMODO_ADMIN_EMAIL:}
  password: ${KOMODO_ADMIN_PASSWORD:}
  given-name: ${KOMODO_ADMIN_GIVENNAME:}
  last-name: ${KOMODO_ADMIN_LASTNAME:}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
      base-path: /management
  endpoint:
    health:
      show-details: always
      show-components: always
    loggers:
      access: READ_ONLY
    metrics:
      access: READ_ONLY
