server:
  port: 8080

logging:
  level:
     '[org.springframework.security]': DEBUG
     '[kjistik.auth_server_komodo.Security]': DEBUG  # More verbose for security packages
     '[kjistik.auth_server_komodo.Exceptions]': WARN
     '[kjistik]': INFO  # Base package level
  file:
    name: logs/auth-server.log
    max-size: 10MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %logger{36} | %X{traceId:-} | %msg%n"
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(| %-5level |){blue}
      %clr(%logger{36}){cyan}
      %clr(| %X{traceId:-} |){magenta}
      %msg%n%throwable

jwt:
  secret-key: ${KOMODO_JWT_SECRET_KEY}
  expiration-time: ${KOMODO_JWT_EXPIRATION_TIME}  
  verification-expiration-time: ${KOMODO_JWT_EMAIL_VERIFICATION_TIME}
  refresh-expiration-time: ${KOMODO_REFRESH_TOKEN_EXPIRATION_TIME}

mailgun:
  key: ${KOMODO_MAILGUN_KEY}
  domain: ${KOMODO_MAILGUN_DOMAIN}

spring:
  data:
    redis:
      host: redis
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  web:
    resources:
      static-locations: classpath:/static/
  r2dbc:
    url: ${KOMODO_DATASOURCE_URL}
    username: ${KOMODO_DATASOURCE_USER}
    password: ${KOMODO_DATASOURCE_PASSWORD}
  komodo:
    domain-url: ${KOMODO_DOMAIN_URL}

# For production monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
      base-path: /management  # Secured separate path
  endpoint:
    health:
      show-details: always
      show-components: always
    loggers:
      access : READ_ONLY
    metrics:
      access: READ_ONLY